# Site
title: Vincent Yang
description: Passionate about efficiency 
url: //www.yangvincent.com
logo: v4.png                                       # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/northern-lights.jpeg                           # this image will be shown on homepage's left block
  post-list: images/bridge.jpeg             # this image will be shown on post list page
  #default-post: images/unsplash-gallery-image-3.jpg   # this image will be shown when post's front matter doesn't specify any image
  default-post: images/city-lights.jpeg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-81484519-1

# Social Links
email:              vincenty.376@gmail.com
#google.plus:        username
#twitter:            username
#facebook:           username
github:             yangvincent
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           vinyang
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username
resume:             resume
#goodreads:             vincentyang

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
